name: "Prepare helm"
description: "Prepares helm by installing helm and python"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1 # Also update in publish.yaml

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      shell: bash
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      shell: bash
      run: ct lint --target-branch ${{ github.event.repository.default_branch }}

    # maybe also do testing with kind