gateway:
  enabled: false
  # -- Name of Gateway Resource. Defaults to: {{ .Release.Name }}-gateway
  name: ""
  # -- List of usable hosts
  hosts: []

  tls:
    # -- Whether to create and apply a TLS-Certificate
    enabled: false
    # -- Whether to redirect all traffic from http to https
    httpsRedirect: false
    # -- Certificate Resource spec.issuerRef
    issuerRef:
      name: letsencrypt-staging
      kind: ClusterIssuer

# configures virtualservice
routing:
  enabled: false
  # -- Hosts, the VirtualService should listen too
  hosts: ["*"]
  # -- HTTPRoute config for deployment, see [istio HTTPRoute](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute)
  deploymentRoute:
    match: 
      - uri:
          prefix: /
  # -- Additional HTTPRoutes, see [istio request routing](https://istio.io/latest/docs/tasks/traffic-management/request-routing/)
  additionalHttp: []
  # -- Gateways for the VirtualService. Will always include this charts' Gateway, if used.
  gateways: []

deployment:
  # -- whether to create deployment, service, ...
  enabled: true
  # -- spec.template.metadata for pods
  metadata:
    annotations: {}
  # -- serviceAccount for pods to use
  serviceAccountName: ""
  # -- Amount of pod replicas
  replicas: 1
  # -- Docker image uri
  image: nginxinc/nginx-unprivileged
  # -- Image pull secrets, useful when interacting with private registy
  imagePullSecrets: {}
  # -- Container-port to expose per Service
  port: 8080

  resources:
    # -- See [kubernetes requests](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container)
    requests:
      cpu: '0'
      memory: '0'

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2

    metrics:
      # -- average cpu utilization, see [kubernetes hpa docs](https://kubernetes.io/de/docs/tasks/run-application/horizontal-pod-autoscale/#details-zum-algorithmus)
      averageUtilizationCpu: ""
      # -- raw HorizontalPodAutoscaler metrics
      additionalMetrics: {}

  configmap:
    enabled: false
    # -- Values for configmap. The values will be passed as container envs, exactly matching the key names.
    values: {}

  # -- Additional [kubernetes container envs](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  env: []
