gateway:
  enabled: false
  # -- Name of Gateway Resource
  # @default -- `{{ .Release.Name }}-gateway`
  name: ""
  # -- List of usable hosts
  hosts: []

  tls:
    # -- Whether to create and apply a TLS-Certificate
    enabled: false
    # -- Whether to redirect all traffic from http to https
    httpsRedirect: false

    # -- the name of the TLS-Certificate secret
    # @default -- `{{ .Release.Name }}-tls`
    credentialName: ""

    # -- Certificate Resource spec.issuerRef
    issuerRef:
      name: letsencrypt-staging
      kind: ClusterIssuer

# configures virtualservice
routing:
  enabled: false
  # -- whether to redirect off of www.
  nonWWWRedirect:
    redirectCode: 301
  # -- Hosts, the VirtualService should listen too
  hosts: ["*"]
  # -- Additional HTTPRoutes, see [istio request routing](https://istio.io/latest/docs/tasks/traffic-management/request-routing/)
  additionalHttp: []
  # -- HTTPRoute config for deployment, see [istio HTTPRoute](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute)
  deploymentRoute:
    match:
      - uri:
          prefix: /
  # -- Gateways for the VirtualService. Will always include this charts' Gateway, if used.
  gateways: []

deployment:
  # -- whether to create deployment, service, ...
  enabled: true
  # -- Deployment Replicas
  replicas: 1
  # -- Docker image uri
  image: nginxinc/nginx-unprivileged
  # -- Container-port to expose per Service
  port: 8080

  # -- Container volume mounts
  volumeMounts: {}

  template:
    # -- template metadata
    metadata:
      annotations: {}
      labels: {}
    # -- template specs
    spec: {}

  resources:
    # -- See [kubernetes requests](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container)
    requests:
      cpu: "0"
      memory: "0"

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2

    metrics:
      # -- average cpu utilization, see [kubernetes hpa docs](https://kubernetes.io/de/docs/tasks/run-application/horizontal-pod-autoscale/#details-zum-algorithmus)
      averageUtilizationCpu: ""
      # -- raw HorizontalPodAutoscaler metrics
      additionalMetrics: {}

  configmap:
    enabled: false
    # -- Values for configmap. The values will be passed as container envs, exactly matching the key names.
    values: {}

  # -- Additional [kubernetes container envs](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  env: []
