{{- if .Values.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  minReplicas: {{ .Values.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment
  metrics:
    {{- if .Values.deployment.autoscaling.metrics.averageUtilizationCpu}}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment.autoscaling.metrics.averageUtilizationCpu }}
    {{- end }}

    {{- if .Values.deployment.autoscaling.metrics.additionalMetrics}}
    {{- toYaml .Values.deployment.autoscaling.metrics.additionalMetrics | nindent 4}}
    {{- end }}
{{- end }}