apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      {{- if (.Values.deployment.metadata).annotations }}
      annotations: {{- toYaml .Values.deployment.metadata.annotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      containers:
        - name: {{ .Release.Name }}-deployment
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          env:
          {{- if .Values.deployment.configmap.enabled }}
          {{- range $key, $value := .Values.deployment.configmap.values }}
            - name: {{$key}}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Release.Name }}-deployment-config
                  key: {{$key}}
          {{- end}}
          {{- end}}
          {{- if .Values.deployment.env }}
          {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end}}
          resources:
            requests:
              cpu: {{ ((.Values.deployment.resources).requests).cpu }}
              memory: {{ ((.Values.deployment.resources).requests).memory }}
