{{ $gatewayName := .Values.gateway.name | default (print .Release.Name "-gateway") -}}
{{ $httpGatewayName := ternary (print $gatewayName "-https-redirect") $gatewayName .Values.gateway.tls.httpsRedirect}}

{{- if .Values.gateway.enabled }}

{{- if .Values.gateway.tls.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $gatewayName }}
spec:
  selector:
    app: istio-ingressgateway
  servers:

  - port:
      number: 443
      name: https
      protocol: HTTPS
    {{- if .Values.gateway.hosts }}
    hosts: {{- toYaml .Values.gateway.hosts | nindent 4 }}
    {{- end }}
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: {{ .Release.Name }}-cert
{{- end }}
---
{{- if or (.Values.gateway.tls.httpsRedirect) (not .Values.gateway.tls.enabled) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $httpGatewayName }}
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    {{- if .Values.gateway.hosts }}
    hosts: {{- toYaml .Values.gateway.hosts | nindent 4 }}
    {{- end }}
    tls:
      httpsRedirect: false
{{- end }}
---
{{- if .Values.gateway.tls.httpsRedirect }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $httpGatewayName }}-vs
spec:
  hosts:
    - "*"
  gateways:
    - {{ $httpGatewayName }}
  http:
    - match:
      - withoutHeaders:
          :path:
            prefix: /.well-known/acme-challenge/
      redirect:
        scheme: https
        redirectCode: 301
{{- end }}

{{- end }}
