{{ $gatewayName := .Values.gateway.name | default (print .Release.Name "-gateway") -}}

{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $gatewayName }}
spec:
  selector:
    app: istio-ingressgateway
  servers:
  {{- if or (.Values.gateway.tls.httpsRedirect) (not .Values.gateway.tls.enabled) }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    {{- if .Values.gateway.hosts }}
    hosts: {{- toYaml .Values.gateway.hosts | nindent 4 }}
    {{- end }}
    tls:
      httpsRedirect: false # sends 301 redirect for http requests
  {{- end }}

  {{- if .Values.gateway.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    {{- if .Values.gateway.hosts }}
    hosts: {{- toYaml .Values.gateway.hosts | nindent 4 }}
    {{- end }}
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: {{ .Release.Name }}-cert
  {{- end }}
---
{{- if .Values.gateway.tls.httpsRedirect }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $gatewayName }}-https-redirect
spec:
  hosts:
    - "*"
  gateways:
    - {{ $gatewayName }}
  http:
    - match:
      - withoutHeaders:
          :path:
            prefix: /.well-known/acme-challenge/
      redirect:
        scheme: https
        redirectCode: 302 # 302 to not mess with risky permanent redirections since a workaround
{{- end }}
{{- end }}
