{{- $hostRedirectCode := 301 }}
{{- $hostRedirectFromHosts := .Values.gateway.hosts }}
{{- $hostRedirectHost := "" }}

{{- if .Values.routing.hostRedirect }}
{{- if (eq (typeOf .Values.routing.hostRedirect) "string") }}
{{- $hostRedirectHost = .Values.routing.hostRedirect }}
{{- $hostRedirectCode = 301 }}
{{- else }}
{{- $hostRedirectHost = .Values.routing.hostRedirect.targetHost }}
{{- $hostRedirectFromHosts = .Values.routing.hostRedirect.redirectFromHosts | default .Values.gateway.hosts }}
{{- $hostRedirectCode = .Values.routing.hostRedirect.redirectCode | default 301 }}
{{- end }}
{{- end}}

{{- if .Values.routing.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
spec:
  hosts: {{- toYaml .Values.routing.hosts | nindent 4 }}
  gateways: 
    {{- if .Values.gateway.enabled }}
    - {{ .Values.gateway.name | default (print .Release.Name "-gateway") }}
    {{- end}}

    {{- if .Values.routing.gateways }}
    {{- toYaml .Values.routing.gateways | nindent 4 }}
    {{- end}}
  http:
    {{- if .Values.routing.additionalHttp }}
    {{- toYaml .Values.routing.additionalHttp | nindent 4}}
    {{- end }}

    {{- if $hostRedirectHost }}
    {{- range (without $hostRedirectFromHosts $hostRedirectHost) }}
    - match:
      - authority:
          exact: {{ . }}
      redirect:
        authority: {{ $hostRedirectHost }}
        redirectCode: {{ $hostRedirectCode }}
    {{- end }}
    {{- end }}


    {{- if .Values.routing.deploymentRoute }}
    - route:
      - destination:
          port:
            number: {{ .Values.deployment.port }}
          host: {{ .Release.Name }}
      {{- toYaml .Values.routing.deploymentRoute | nindent 6}}
     
    {{- end }}
{{- end }}

