{{- $nonWWWRedirectCode := 301 }}
{{- if .Values.routing.nonWWWRedirect }}
{{- if (eq (typeOf .Values.routing.nonWWWRedirect) "bool") }}
{{- $nonWWWRedirectCode = 301 }}
{{- else }}
{{- $nonWWWRedirectCode = .Values.routing.nonWWWRedirect.redirectCode }}
{{- end }}
{{- end}}

{{- if .Values.routing.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
spec:
  hosts: {{- toYaml .Values.routing.hosts | nindent 4 }}
  gateways: 
    {{- if .Values.gateway.enabled }}
    - {{ .Values.gateway.name | default (print .Release.Name "-gateway") }}
    {{- end}}

    {{- if .Values.routing.gateways }}
    {{- toYaml .Values.routing.gateways | nindent 4 }}
    {{- end}}
  http:
    {{- if .Values.routing.nonWWWRedirect }}
    {{- range .Values.gateway.hosts }}
    {{- if and (hasPrefix "www." . ) (not (eq . "www")) }}
    - match:
      - authority:
          exact: {{ . }}
      redirect:
        authority: {{ . | replace "www." "" }}
        redirectCode: {{ $nonWWWRedirectCode }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.routing.additionalHttp }}
    {{- toYaml .Values.routing.additionalHttp | nindent 4}}
    {{- end }}

    {{- if .Values.routing.deploymentRoute }}
    - route:
      - destination:
          port:
            number: {{ .Values.deployment.port }}
          host: {{ .Release.Name }}
      {{- toYaml .Values.routing.deploymentRoute | nindent 6}}
     
    {{- end }}
{{- end }}

