name: lint/test charts

on:
  workflow_call:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: prepare helm
        uses: ./.github/actions/prepare-helm

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        shell: bash
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        shell: bash
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run helm-docs
        run: scripts/helm-docs.sh
