name: Release Charts

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci-workflow.yml
  
  release:
    permissions:
      contents: write
    timeout-minutes: 10
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: prepare helm
        uses: ./.github/actions/prepare-helm

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
